version: '3.7'

services:

  lp-client:
    container_name: agile-client
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/client'
      - '/client/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - COMPOSE_CONVERT_WINDOWS_PATHS=1
